name: Terraform Manual Run

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        default: dev
        type: choice
        options:
          - production
      environment_directory:
        description: 'Select Environment Directory'
        required: true
        default: dev
        type: choice
        options:
          - stage
          - prod

      directory:
        description: 'Select Terraform Module'
        required: true
        default: frontend-service
        type: choice
        options:
          - artifact-registry
          - frontend-service
          - backend-service
          - storage

      command:
        description: 'Select Terraform Command'
        required: true
        default: plan
        type: choice
        options:
          - init
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0
      - name: Setup GCP credentials
        env:
          GCP_CREDENTIALS_BASE64: ${{ secrets.GCP_CREDENTIALS_BASE64 }}
          GCP_PROJECT_ID: ${{ secrets.TF_VAR_PROJECT_ID }}
        run: |
          printf "%s" "$GCP_CREDENTIALS_BASE64" | base64 --decode > "${HOME}/gcp-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"
          gcloud config set project "$GCP_PROJECT_ID"

      - name: Run selected Terraform command
        env:
          TF_VAR_AI_INTERVIEW_LINK: ${{ secrets.TF_VAR_AI_INTERVIEW_LINK }}
          TF_VAR_APP_IMAGE_NAME: ${{ secrets.TF_VAR_APP_IMAGE_NAME }}
          TF_VAR_BACKEND_CORS_ORIGINS: ${{ secrets.TF_VAR_BACKEND_CORS_ORIGINS }}
          TF_VAR_BACKEND_SERVICE: ${{ secrets.TF_VAR_BACKEND_SERVICE }}
          TF_VAR_BUCKET: ${{ secrets.TF_VAR_BUCKET }}
          TF_VAR_BUCKET_NAME: ${{ secrets.TF_VAR_BUCKET_NAME }}
          TF_VAR_CHAT_GENAI: ${{ secrets.TF_VAR_CHAT_GENAI }}
          TF_VAR_CLOUD_STORAGE_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.TF_VAR_CLOUD_STORAGE_AUTH_PROVIDER_X509_CERT_URL }}
          TF_VAR_CLOUD_STORAGE_AUTH_URI: ${{ secrets.TF_VAR_CLOUD_STORAGE_AUTH_URI }}
          TF_VAR_CLOUD_STORAGE_CLIENT_EMAIL: ${{ secrets.TF_VAR_CLOUD_STORAGE_CLIENT_EMAIL }}
          TF_VAR_CLOUD_STORAGE_CLIENT_ID: ${{ secrets.TF_VAR_CLOUD_STORAGE_CLIENT_ID }}
          TF_VAR_CLOUD_STORAGE_CLIENT_X509_CERT_URL: ${{ secrets.TF_VAR_CLOUD_STORAGE_CLIENT_X509_CERT_URL }}
          TF_VAR_CLOUD_STORAGE_PRIVATE_KEY: ${{ secrets.TF_VAR_CLOUD_STORAGE_PRIVATE_KEY }}
          TF_VAR_CLOUD_STORAGE_PRIVATE_KEY_ID: ${{ secrets.TF_VAR_CLOUD_STORAGE_PRIVATE_KEY_ID }}
          TF_VAR_CLOUD_STORAGE_PROJECT_ID: ${{ secrets.TF_VAR_CLOUD_STORAGE_PROJECT_ID }}
          TF_VAR_CLOUD_STORAGE_TOKEN_URI: ${{ secrets.TF_VAR_CLOUD_STORAGE_TOKEN_URI }}
          TF_VAR_CLOUD_STORAGE_TYPE: ${{ secrets.TF_VAR_CLOUD_STORAGE_TYPE }}
          TF_VAR_CURRENT_USER: ${{ secrets.TF_VAR_CURRENT_USER }}
          TF_VAR_DATABASE_URL: ${{ secrets.TF_VAR_DATABASE_URL }}
          TF_VAR_DB_MAX_CONNECTIONS: ${{ secrets.TF_VAR_DB_MAX_CONNECTIONS }}
          TF_VAR_DB_MAX_OVERFLOW: ${{ secrets.TF_VAR_DB_MAX_OVERFLOW }}
          TF_VAR_DB_PASSWORD: ${{ secrets.TF_VAR_DB_PASSWORD }}
          TF_VAR_DB_POSTGRESDB_DATABASE: ${{ secrets.TF_VAR_DB_POSTGRESDB_DATABASE }}
          TF_VAR_DB_POSTGRESDB_PORT: ${{ secrets.TF_VAR_DB_POSTGRESDB_PORT }}
          TF_VAR_DB_POSTGRESDB_USER: ${{ secrets.TF_VAR_DB_POSTGRESDB_USER }}
          TF_VAR_DB_RESERVED_CONNECTIONS: ${{ secrets.TF_VAR_DB_RESERVED_CONNECTIONS }}
          TF_VAR_DB_TYPE: ${{ secrets.TF_VAR_DB_TYPE }}
          TF_VAR_EXECUTIONS_MODE: ${{ secrets.TF_VAR_EXECUTIONS_MODE }}
          TF_VAR_FE_URL: ${{ secrets.TF_VAR_FE_URL }}
          TF_VAR_FIREBASE_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.TF_VAR_FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}
          TF_VAR_FIREBASE_AUTH_URI: ${{ secrets.TF_VAR_FIREBASE_AUTH_URI }}
          TF_VAR_FIREBASE_CLIENT_EMAIL: ${{ secrets.TF_VAR_FIREBASE_CLIENT_EMAIL }}
          TF_VAR_FIREBASE_CLIENT_ID: ${{ secrets.TF_VAR_FIREBASE_CLIENT_ID }}
          TF_VAR_FIREBASE_CLIENT_X509_CERT_URL: ${{ secrets.TF_VAR_FIREBASE_CLIENT_X509_CERT_URL }}
          TF_VAR_FIREBASE_PRIVATE_KEY: ${{ secrets.TF_VAR_FIREBASE_PRIVATE_KEY }}
          TF_VAR_FIREBASE_PROJECT_ID: ${{ secrets.TF_VAR_FIREBASE_PROJECT_ID }}
          TF_VAR_FIREBASE_TOKEN_URI: ${{ secrets.TF_VAR_FIREBASE_TOKEN_URI }}
          TF_VAR_FIREBASE_TYPE: ${{ secrets.TF_VAR_FIREBASE_TYPE }}
          TF_VAR_FIREBASE_UNIVERSE_DOMAIN: ${{ secrets.TF_VAR_FIREBASE_UNIVERSE_DOMAIN }}
          TF_VAR_FOLDER: ${{ secrets.TF_VAR_FOLDER }}
          TF_VAR_FROM_ADDRESS: ${{ secrets.TF_VAR_FROM_ADDRESS }}
          TF_VAR_FRONTEND_SERVICE: ${{ secrets.TF_VAR_FRONTEND_SERVICE }}
          TF_VAR_GEMINI_API_KEY: ${{ secrets.TF_VAR_GEMINI_API_KEY }}
          TF_VAR_GEMINI_KEY_MAX_CALLS_PER_MINUTE: ${{ secrets.TF_VAR_GEMINI_KEY_MAX_CALLS_PER_MINUTE }}
          TF_VAR_GENAI: ${{ secrets.TF_VAR_GENAI }}
          TF_VAR_GOOGLE_MEET_CLIENT_ID: ${{ secrets.TF_VAR_GOOGLE_MEET_CLIENT_ID }}
          TF_VAR_GOOGLE_MEET_CLIENT_SECRET: ${{ secrets.TF_VAR_GOOGLE_MEET_CLIENT_SECRET }}
          TF_VAR_GOOGLE_MEET_REDIRECT_URL: ${{ secrets.TF_VAR_GOOGLE_MEET_REDIRECT_URL }}
          TF_VAR_IMAGE_NAME: ${{ secrets.TF_VAR_IMAGE_NAME }}
          TF_VAR_INTEGRATIONS_SECRET_KEY: ${{ secrets.TF_VAR_INTEGRATIONS_SECRET_KEY }}
          TF_VAR_JOB_SECRET_KEY: ${{ secrets.TF_VAR_JOB_SECRET_KEY }}
          TF_VAR_KEY_1: ${{ secrets.TF_VAR_KEY_1 }}
          TF_VAR_KEY_2: ${{ secrets.TF_VAR_KEY_2 }}
          TF_VAR_KEY_3: ${{ secrets.TF_VAR_KEY_3 }}
          TF_VAR_KEY_4: ${{ secrets.TF_VAR_KEY_4 }}
          TF_VAR_KEY_5: ${{ secrets.TF_VAR_KEY_5 }}
          TF_VAR_LINKEDIN_CLIENT_ID: ${{ secrets.TF_VAR_LINKEDIN_CLIENT_ID }}
          TF_VAR_LINKEDIN_CLIENT_SECRET: ${{ secrets.TF_VAR_LINKEDIN_CLIENT_SECRET }}
          TF_VAR_LINKEDIN_REDIRECT_URL: ${{ secrets.TF_VAR_LINKEDIN_REDIRECT_URL }}
          TF_VAR_MAX_INSTANCE_COUNT: ${{ secrets.TF_VAR_MAX_INSTANCE_COUNT }}
          TF_VAR_N8N_BASIC_AUTH_ACTIVE: ${{ secrets.TF_VAR_N8N_BASIC_AUTH_ACTIVE }}
          TF_VAR_N8N_BASIC_AUTH_PASSWORD: ${{ secrets.TF_VAR_N8N_BASIC_AUTH_PASSWORD }}
          TF_VAR_N8N_BASIC_AUTH_USER: ${{ secrets.TF_VAR_N8N_BASIC_AUTH_USER }}
          TF_VAR_N8N_ENCRYPTION_KEY: ${{ secrets.TF_VAR_N8N_ENCRYPTION_KEY }}
          TF_VAR_N8N_HOST: ${{ secrets.TF_VAR_N8N_HOST }}
          TF_VAR_N8N_PROTOCOL: ${{ secrets.TF_VAR_N8N_PROTOCOL }}
          TF_VAR_N8N_RUN_COMMAND: ${{ secrets.TF_VAR_N8N_RUN_COMMAND }}
          TF_VAR_N8N_SERVICE_NAME: ${{ secrets.TF_VAR_N8N_SERVICE_NAME }}
          TF_VAR_OTPLESS_CLIENT_ID: ${{ secrets.TF_VAR_OTPLESS_CLIENT_ID }}
          TF_VAR_OTPLESS_CLIENT_SECRET: ${{ secrets.TF_VAR_OTPLESS_CLIENT_SECRET }}
          TF_VAR_PERSIMMON_DATA_BUCKET: ${{ secrets.TF_VAR_PERSIMMON_DATA_BUCKET }}
          TF_VAR_PERSIMMON_IMAGES_BUCKET: ${{ secrets.TF_VAR_PERSIMMON_IMAGES_BUCKET }}
          TF_VAR_PROJECT_ID: ${{ secrets.TF_VAR_PROJECT_ID }}
          TF_VAR_QUEUE_BULL_REDIS_PORT: ${{ secrets.TF_VAR_QUEUE_BULL_REDIS_PORT }}
          TF_VAR_REDIS_URL: ${{ secrets.TF_VAR_REDIS_URL }}
          TF_VAR_REGION: ${{ secrets.TF_VAR_REGION }}
          TF_VAR_REGION_CLOUDRUN: ${{ secrets.TF_VAR_REGION_CLOUDRUN }}
          TF_VAR_REGION_CONTAINER_REPO: ${{ secrets.TF_VAR_REGION_CONTAINER_REPO }}
          TF_VAR_REPOSITORY_ID: ${{ secrets.TF_VAR_REPOSITORY_ID }}
          TF_VAR_SECRET_KEY: ${{ secrets.TF_VAR_SECRET_KEY }}
          TF_VAR_SMTP_PASSWORD: ${{ secrets.TF_VAR_SMTP_PASSWORD }}
          TF_VAR_SMTP_USER: ${{ secrets.TF_VAR_SMTP_USER }}
          TF_VAR_SOLR_BASE_URL: ${{ secrets.TF_VAR_SOLR_BASE_URL }}
          TF_VAR_TEMPLATE_EMAIL_ID: ${{ secrets.TF_VAR_TEMPLATE_EMAIL_ID }}
          TF_VAR_TIMEOUT: ${{ secrets.TF_VAR_TIMEOUT }}
          TF_VAR_TOPIC_NAME: ${{ secrets.TF_VAR_TOPIC_NAME }}
          TF_VAR_VOLUME_MOUNT_PATH: ${{ secrets.TF_VAR_VOLUME_MOUNT_PATH }}
          TF_VAR_WEB_CONCURRENCY: ${{ secrets.TF_VAR_WEB_CONCURRENCY }}
          TF_VAR_N8N_IMAGE_NAME: ${{ secrets.TF_VAR_N8N_IMAGE_NAME }}
        run: |
          ENV_DIR=${{ github.event.inputs.environment_directory }}
          DIR=${{ github.event.inputs.directory }}
          CMD=${{ github.event.inputs.command }}

          echo "Running Terraform $CMD for module '$DIR' in environment '$ENV_DIR'"
          cd "infra/$ENV_DIR/$DIR"
          terraform $CMD -input=false
          cd - >/dev/null
